# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchFromGitHub,
}: {
  gh-poi = {
    pname = "gh-poi";
    version = "v0.9.1";
    src = fetchFromGitHub {
      owner = "seachicken";
      repo = "gh-poi";
      rev = "v0.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-7KZSZsYfo9zZ0HSg5yLDNTlwb30byD73kqMNHc0tQpo=";
    };
    vendorSha256 = "sha256-D/YZLwwGJWCekq9mpfCECzJyJ/xSlg7fC6leJh+e8i0=";
  };
  imhex = {
    pname = "imhex";
    version = "v1.29.0";
    src = fetchFromGitHub {
      owner = "WerWolv";
      repo = "imhex";
      rev = "v1.29.0";
      fetchSubmodules = false;
      sha256 = "sha256-Ktwms/IrupbqWubPIEJxJVYCAdhPT1d1dy5m/E4y5q4=";
    };
  };
}
