# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}: {
  gh-poi = {
    pname = "gh-poi";
    version = "v0.9.1";
    src = fetchFromGitHub {
      owner = "seachicken";
      repo = "gh-poi";
      rev = "v0.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-7KZSZsYfo9zZ0HSg5yLDNTlwb30byD73kqMNHc0tQpo=";
    };
    vendorSha256 = "sha256-D/YZLwwGJWCekq9mpfCECzJyJ/xSlg7fC6leJh+e8i0=";
  };
  imhex = {
    pname = "imhex";
    version = "v1.29.0";
    src = fetchFromGitHub {
      owner = "WerWolv";
      repo = "imhex";
      rev = "v1.29.0";
      fetchSubmodules = true;
      sha256 = "sha256-dghyv7rpqGs5dt51ziAaeb/Ba7rGEcJ54AYKRJ2xXuk=";
    };
  };
  vscord = {
    pname = "vscord";
    version = "5.1.9";
    src = fetchurl {
      url = "https://LeonardSSH.gallery.vsassets.io/_apis/public/gallery/publisher/LeonardSSH/extension/vscord/5.1.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscord-5.1.9.zip";
      sha256 = "sha256-fyR0oZ/PmmXBrRKmQatga/NPkf8G9Bd0cHANHBgMvCU=";
    };
  };
}
